//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public double ShoeSize { get; set; }
        public int Qty { get; set; }
        public string Name { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public double TotalMoney { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LogisticsCompany { get; set; }
        public string LogisticsCode { get; set; }
        public string Status { get; set; }
        public Nullable<double> Price { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string CustomerIP { get; set; }
    }
}
