//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class OrderManageDbContext : DbContext
    {
        public OrderManageDbContext()
            : base("name=OrderManageDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order> Orders { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual string GenerateOrderId()
        {
            ObjectResult<string> result =((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GenerateOrderId");
            return result.FirstOrDefault();
        }
    }
}
